on: [workflow_dispatch] 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11.8"

    - run: pip3 install poetry pyinstaller
      working-directory: ./nexta_analysis
    - run: poetry config virtualenvs.create false
      working-directory: ./nexta_analysis
    - run: poetry install --with pyinstaller
      working-directory: ./nexta_analysis
    - run: pyinstaller -F read_time_gui.py
      working-directory: ./nexta_analysis
    # Optionally verify that it works (provided that it does not need user interaction)
    #- run: ./dist/read_time_gui/read_time_gui --help
    - uses: actions/upload-artifact@v4
      with:
        path: nexta_analysis/dist/*
        name: ${{ matrix.os }}-${{ strategy.job-index }}
